FROM python:latest

# Set the working directory in the container
# WORKDIR /usr/src/app

# Copy the dependencies file to the working directory
# COPY ../requirements.txt /requirements.txt

# Install any dependencies
# RUN apt-get update && pip install --upgrade pip
# RUN pip install --no-cache-dir -r requirements.txt

# Copy the content of the local src directory to the working directory
# COPY . .

